CREATE TABLE IF NOT EXISTS [Posts] (
	[id] INTEGER PRIMARY KEY UNIQUE,
	[name] VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS [Tags] (
	[id] INTEGER PRIMARY KEY UNIQUE,
	[name] VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS [PostsTags] (
	[postId] INTEGER,
	[tagId] INTEGER
);