CREATE TABLE IF NOT EXISTS [food] ([id] INTEGER PRIMARY KEY UNIQUE);
CREATE TABLE IF NOT EXISTS [ingredients] ([id] INTEGER PRIMARY KEY UNIQUE);
CREATE TABLE IF NOT EXISTS [foods_ingredients] ([food_id] INTEGER, [ingredients_id] INTEGER);
