CREATE TABLE IF NOT EXISTS [Programmers] ([id] INTEGER PRIMARY KEY UNIQUE);
CREATE TABLE IF NOT EXISTS [Projects] ([id] INTEGER PRIMARY KEY UNIQUE);
CREATE TABLE IF NOT EXISTS [ProjectsProgrammers] ([projectId] INTEGER, [programmersId] INTEGER);
