CREATE TABLE Offices (
	officeCode VARCHAR(10) NOT NULL PRIMARY KEY UNIQUE,
	city VARCHAR(50) NOT NULL,
	phone VARCHAR(50) NOT NULL,
	addressLine1 VARCHAR(50) NOT NULL,
	addressLine2 VARCHAR(50),
	state VARCHAR(50),
	country VARCHAR(50) NOT NULL,
	postalCode VARCHAR(15) NOT NULL,
	territory VARCHAR(10) NOT NULL,
	position INTEGER DEFAULT 0
);


CREATE TABLE Employees (
	employeeNumber INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	lastName VARCHAR(50) NOT NULL,
	firstName VARCHAR(50) NOT NULL,
	extension VARCHAR(10) NOT NULL,
	email VARCHAR(100) NOT NULL,
	officeCode VARCHAR(10) NOT NULL, -- REFERENCES Offices ON DELETE RESTRICT,
	reportsTo INTEGER NULL, -- REFERENCES Employees ON DELETE RESTRICT,
	jobTitle VARCHAR(50) NOT NULL
);

CREATE VIEW Managers AS
	SELECT * FROM Employees WHERE reportsTo IS NULL;

CREATE TABLE Customers (
	customerNumber INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	customerName VARCHAR(50) NOT NULL,
	contactLastName VARCHAR(50) NOT NULL,
	contactFirstName VARCHAR(50) NOT NULL,
	phone VARCHAR(50) NOT NULL,
	addressLine1 VARCHAR(50) NOT NULL,
	addressLine2 VARCHAR(50) NULL,
	city VARCHAR(50) NOT NULL,
	state VARCHAR(50) NULL,
	postalCode VARCHAR(15) NULL,
	country VARCHAR(50) NOT NULL,
	employeeNumber INTEGER NULL, -- REFERENCES Employees ON DELETE RESTRICT,
	creditLimit DOUBLE NULL
);

CREATE TABLE Payments (
	customerNumber INTEGER NOT NULL, -- REFERENCES Customers ON DELETE CASCADE,
	checkNumber VARCHAR(50) NOT NULL,
	paymentDate DATETIME NOT NULL,
	amount DOUBLE NOT NULL,
	PRIMARY KEY (customerNumber, checkNumber)
);

CREATE TABLE ProductLines(
	productLine VARCHAR(50) NOT NULL PRIMARY KEY UNIQUE,
	textDescription VARCHAR(4000) NULL,
	htmlDescription MEDIUMTEXT NULL,
	image MEDIUMBLOB NULL
);


CREATE TABLE Products (
	productCode VARCHAR(15) NOT NULL NOT NULL PRIMARY KEY UNIQUE,
	productName VARCHAR(70) NOT NULL,
	productLine VARCHAR(50) NOT NULL, -- REFERENCES ProductLines ON DELETE CASCADE,
	productScale VARCHAR(10) NOT NULL,
	productVendor VARCHAR(50) NOT NULL,
	productDescription TEXT NOT NULL,
	quantityInStock SMALLINT NOT NULL,
	buyPrice DOUBLE NOT NULL,
	MSRP DOUBLE NOT NULL
);


CREATE TABLE Orders (
	orderNumber INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	orderDate TIMESTAMP NOT NULL,
	requiredDate TIMESTAMP NOT NULL,
	shippedDate TIMESTAMP NULL,
	status VARCHAR(15) NOT NULL,
	comments TEXT NULL,
	customerNumber INTEGER NOT NULL -- REFERENCES Customers ON DELETE CASCADE
);


CREATE TABLE OrderDetails (
	orderNumber INTEGER NOT NULL, -- REFERENCES Orders ON DELETE CASCADE,
	productCode VARCHAR(15) NOT NULL, -- REFERENCES Products ON DELETE RESTRICT,
	quantityOrdered INTEGER NOT NULL,
	priceEach DOUBLE NOT NULL,
	orderLineNumber SMALLINT NOT NULL,
	PRIMARY KEY (orderNumber, productCode)
);