CREATE TABLE IF NOT EXISTS [guests] ([id] INTEGER PRIMARY KEY UNIQUE, [name] VARCHAR(64), [belongs_to] INTEGER);
CREATE TABLE IF NOT EXISTS [cars] ([id] INTEGER PRIMARY KEY UNIQUE, [guest_id] INTEGER);
CREATE TABLE IF NOT EXISTS [guides] ([id] INTEGER PRIMARY KEY UNIQUE, [name] VARCHAR(64));
