CREATE TABLE IF NOT EXISTS [Authors] (
	[id] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE CHECK ([id] > 0),
	[login] VARCHAR(64)  NOT NULL UNIQUE,
	[email] VARCHAR(128)  NOT NULL UNIQUE,
	[firstname] VARCHAR(64)  NOT NULL,
	[lastname] VARCHAR(64)  NOT NULL,
	[credit] INTEGER  DEFAULT 0 NOT NULL
);