CREATE TABLE IF NOT EXISTS [Consumers] (
  [id] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE CHECK ([id] > 0),
  [firstname] VARCHAR(45) NOT NULL,
  [lastname] VARCHAR(45) NOT NULL,
  [street] VARCHAR(45) NOT NULL,
  [city] VARCHAR(45) NOT NULL,
  [nid] VARCHAR(11) NOT NULL UNIQUE,
  [email] VARCHAR(45) NOT NULL UNIQUE
);
