CREATE TABLE Companies (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	clientOf INTEGER NULL REFERENCES Companies ON DELETE CASCADE,
	isFirm BOOLEAN NOT NULL DEFAULT 1,
	name VARCHAR(255)
);

CREATE TABLE People (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	companyId INTEGER NULL REFERENCES Companies ON DELETE CASCADE,
	name VARCHAR(255)
);

CREATE VIEW Firms AS
SELECT id, name FROM Companies WHERE isFirm = 1;

CREATE VIEW Clients AS
SELECT id, clientOf, name FROM Companies WHERE isFirm = 0;